/**
 * Model factory — creates the right LangChain chat model based on LLM_PROVIDER.
 *
 * Supported providers:
 *   "openai"  — ChatOpenAI (also covers OpenRouter, Z.ai, any OpenAI-compatible)
 *   "google"  — ChatGoogleGenerativeAI (native Google Gemini via GOOGLE_API_KEY)
 *
 * The factory returns a `BaseChatModel` so callers never import provider packages.
 */

import type { BaseChatModel } from "@langchain/core/language_models/chat_models";

export type LlmProvider = "openai" | "google";

export interface ModelConfig {
  provider: LlmProvider;

  // --- OpenAI-compatible fields (provider === "openai") ---
  openaiBaseUrl?: string;
  openaiApiKey?: string;
  /** Model identifier on the provider, e.g. "google/gemini-3-flash-preview" (OpenRouter) */
  model: string;

  // --- Google-native fields (provider === "google") ---
  googleApiKey?: string;

  // --- Common optional fields ---
  temperature?: number;
}

/**
 * Detect the intended provider from env vars.
 *
 * Priority:
 *   1. Explicit `LLM_PROVIDER` env var
 *   2. If `GOOGLE_API_KEY` is set (and no OPENAI vars), default to "google"
 *   3. Otherwise "openai"
 */
export function detectProvider(): LlmProvider {
  const explicit = process.env.LLM_PROVIDER?.trim().toLowerCase();
  if (explicit === "google") return "google";
  if (explicit === "openai") return "openai";

  // Auto-detect: if GOOGLE_API_KEY is present and OPENAI_API_KEY is absent → google
  if (process.env.GOOGLE_API_KEY && !process.env.OPENAI_API_KEY) {
    return "google";
  }

  return "openai";
}

/**
 * Create a LangChain `BaseChatModel` from a provider-agnostic config.
 */
export async function createChatModel(
  config: ModelConfig,
): Promise<BaseChatModel> {
  switch (config.provider) {
    case "google":
      return createGoogleModel(config);
    case "openai":
    default:
      return createOpenAIModel(config);
  }
}

// ---------------------------------------------------------------------------
// Provider-specific constructors (lazy-imported so unused providers don't load)
// ---------------------------------------------------------------------------

async function createOpenAIModel(config: ModelConfig): Promise<BaseChatModel> {
  const { ChatOpenAI } = await import("@langchain/openai");

  return new ChatOpenAI({
    model: config.model,
    apiKey: config.openaiApiKey,
    configuration: {
      baseURL: config.openaiBaseUrl,
    },
    temperature: config.temperature ?? 0,
  });
}

async function createGoogleModel(config: ModelConfig): Promise<BaseChatModel> {
  const { ChatGoogleGenerativeAI } = await import("@langchain/google-genai");

  const model = new ChatGoogleGenerativeAI({
    model: config.model,
    apiKey: config.googleApiKey || process.env.GOOGLE_API_KEY,
    temperature: config.temperature ?? 0,
  });

  // Patch bindTools to strip JSON Schema keywords that Gemini's API rejects.
  // The upstream `removeAdditionalProperties` only strips `additionalProperties`,
  // `$schema`, and `strict` — but Zod v4 can emit `exclusiveMinimum`,
  // `exclusiveMaximum`, `minItems`, `maxItems`, `minLength`, `maxLength`, etc.
  // that the Gemini FunctionDeclarationSchema doesn't support.
  patchBindToolsForGemini(model);

  return model;
}

// ---------------------------------------------------------------------------
// Gemini schema sanitizer
// ---------------------------------------------------------------------------

/**
 * JSON Schema keywords that Gemini's FunctionDeclarationSchema does NOT accept.
 * These get generated by Zod → JSON Schema conversion but cause 400 errors.
 */
const GEMINI_UNSUPPORTED_KEYWORDS = new Set([
  "exclusiveMinimum",
  "exclusiveMaximum",
  "minItems",
  "maxItems",
  "minLength",
  "maxLength",
  "minimum",
  "maximum",
  "multipleOf",
  "pattern",
  "uniqueItems",
  "default",
  "$schema",
  "additionalProperties",
  "strict",
]);

/**
 * Recursively strip unsupported JSON Schema keywords from an object tree
 * and fix `required` arrays to only reference existing properties.
 */
function stripUnsupportedGeminiProps(obj: unknown): unknown {
  if (Array.isArray(obj)) {
    return obj.map(stripUnsupportedGeminiProps);
  }
  if (obj !== null && typeof obj === "object") {
    const cleaned: Record<string, unknown> = {};
    for (const key in obj as Record<string, unknown>) {
      if (GEMINI_UNSUPPORTED_KEYWORDS.has(key)) continue;
      cleaned[key] = stripUnsupportedGeminiProps(
        (obj as Record<string, unknown>)[key],
      );
    }

    // Fix `required` array: only keep entries that match keys in `properties`.
    // Zod's .optional().default() can produce schemas where `required` lists
    // property names that don't appear in `properties`, which Gemini rejects.
    const req = cleaned.required;
    const props = cleaned.properties;

    if (Array.isArray(req)) {
      if (props && typeof props === "object") {
        const newReq: string[] = [];
        for (let i = 0; i < req.length; i++) {
          const k = req[i];
          if (Object.prototype.hasOwnProperty.call(props, k)) {
            newReq.push(k as string);
          }
        }
        if (newReq.length > 0) {
          cleaned.required = newReq;
        } else {
          delete cleaned.required;
        }
      } else if (req.length === 0) {
        delete cleaned.required;
      }
    }

    return cleaned;
  }
  return obj;
}

/**
 * Monkey-patch `bindTools` on a ChatGoogleGenerativeAI instance so that tool
 * schemas are sanitized before reaching the API.
 */
function patchBindToolsForGemini(model: BaseChatModel): void {
  const originalBindTools = (model as any).bindTools;
  if (!originalBindTools) return;

  (model as any).bindTools = function (tools: any[], kwargs?: any) {
    const sanitizedTools = tools.map((t: any) => {
      // LangChain StructuredTool — has a `schema` property (Zod schema)
      // and gets converted to JSON inside convertToolsToGenAI.
      // We can't easily intercept the Zod→JSON step so instead we wrap
      // the tool's toJSON / schema output.
      //
      // For raw function declarations (already JSON), strip directly.
      if (t?.function?.parameters) {
        return {
          ...t,
          function: {
            ...t.function,
            parameters: stripUnsupportedGeminiProps(t.function.parameters),
          },
        };
      }
      return t;
    });
    return originalBindTools.call(this, sanitizedTools, kwargs);
  };

  // Also patch invocationParams which handles tools passed via options
  const originalInvocationParams = (model as any).invocationParams;
  if (originalInvocationParams) {
    (model as any).invocationParams = function (options: any) {
      const result = originalInvocationParams.call(this, options);
      if (result?.tools) {
        result.tools = result.tools.map((toolGroup: any) => {
          if (toolGroup?.functionDeclarations) {
            return {
              ...toolGroup,
              functionDeclarations: toolGroup.functionDeclarations.map(
                (fd: any) =>
                  fd.parameters
                    ? {
                        ...fd,
                        parameters: stripUnsupportedGeminiProps(fd.parameters),
                      }
                    : fd,
              ),
            };
          }
          return toolGroup;
        });
      }
      return result;
    };
  }
}
